### ISSUE TITLE
make devrel errors out with R18

### ISSUE THREAD

**Issue by gyanaggarwal** [mrallen1/udon#4]
==> getopt (compile)
ERROR: OTP release 18 does not match required regex R16|17
ERROR: compile failed while processing /Users/gyanendraaggarwal/udon/udon/deps/getopt: rebar_abort
make: **\* [compile] Error 1

**Comment by jadeallenx** [comment]
Thanks for opening a ticket. I'll see what I can do about getting 18 and 19 supported on this project.

**Comment by jadeallenx** [comment]
OK, for the record: https://github.com/mrallen1/udon_ng is the "next generation" application that works with OTP 18 and 19. (OTP 20 is on the way but not yet complete.)
